### ISSUE TITLE
6.1.2 not booting

### ISSUE THREAD

**Issue by albyvar** [parrotgeek1/Pluvia#1]
Hi, I used your tool to get 6.1.3 and it worked.
But with 6.1.2 all I get is a yellow screen.

Great work anyway

**Comment by parrotgeek1** [comment]
I swear I tried it. I'll check again later today.

**Comment by parrotgeek1** [comment]
Can you try again? I replaced the 6.1.2 bundle with Dora's.

**Comment by parrotgeek1** [comment]
This is fixed in the upcoming Beta 2
