### ISSUE TITLE
Segmentation fault issue

### ISSUE THREAD

**Issue by H8ph0ne** [parrotgeek1/Pluvia#10]
Hi i'm getting this error, i hope you can resolve it
Creating patched IPSW (this will take several minutes)
scripts/03_createIPSW.sh: line 40:  2637 Segmentation fault      (core dumped) ./tools/ipsw "$1" work/tmp.ipsw $extrasbegin -ramdiskgrow 600 work/iBEC.tar $extras > /dev/null.

**Comment by parrotgeek1** [comment]
Are you using the version from releases page? What Mac OS version?

**Comment by H8ph0ne** [comment]
yes, from the releases page, and i used OSX 10.9 & Linux mint 19, got the same error

**Comment by parrotgeek1** [comment]
It does not support Linux. It only supports Mac OS 10.11+
