### ISSUE TITLE
Hacktivate Iphone 4 

### ISSUE THREAD

**Issue by NO-ob** [parrotgeek1/Pluvia#16]
Is there any way to hacktivate with this? I did try using a sn0wbreeze ipsw but it fails to flash properly

he system partition now has a total HFS+ capacity of 1350 MB
entering ramrod_probe_media
device partitioning scheme is GPT
find_filesystem_partitions: storage=/dev/disk0s1 system=/dev/disk0s1s1 data=/dev/disk0s1s2
entering unmount_filesystems
entering ramrod_ticket_update
root-ticket-hash: <CFData 0x1d55fc30 [0x2c6100]>{length = 20, capacity = 20, bytes = 0x0000000000000000000000000000000000000000}
ticket_hash: 332C5CCA81A2B09CC63E3A9487922D9674192646
failed to update ticket: 3
0: RamrodErrorDomain/3: ramrod_ticket_update: invalid ticket
unable to convert ramrod error 3

ERROR: Unable to successfully restore device
ERROR: Unable to restore device

**Comment by parrotgeek1** [comment]
There isn’t and that’s somewhat intentional (iCloud lock)
