### ISSUE TITLE
iMessage slow to activate or sometimes wont activate at all

### ISSUE THREAD

**Issue by animeking9901** [parrotgeek1/Pluvia#21]
iMessage was working on 6.1.3 but I had to restore my phone due to my own stupidity,but here goes
Activated before but now refuses to activate unless I use email instead of my number
tried both 3g and WiFi
Carrier:TracFone ATT Sim
SMS/MMS send/receive works
calling and receiving calls works
data works after changing apn to reseller
Tried turning iMessage off and on
Tried rebooting
Not hacktivated
ipsw was made with JB included
I do not currently have Mac access,i rarely get access to a local college mac
Any on device suggestions I've missed i'm all ears
Edit:Still using 6.1.3 btw

**Comment by parrotgeek1** [comment]
iMessage is very flaky regarding activation on iOS 6. It has nothing to do with Pluvia.
