### ISSUE TITLE
Cannot make IPSW

### ISSUE THREAD

**Issue by festo95** [parrotgeek1/Pluvia#22]
Hi your project looks very cool but I'm faceing an issue tring to make the IPSW for 5.1.1 and 6.1.3
Here is the code :
./make_ipsw.sh /Desktop/iPhone3\,1_5.1.1_9B206_Restore.ipsw
Using cached iBoot keys for iPhone3,1 iOS 5.1.1 (9B206)
Extracting iBoot from IPSW
Patching iBoot
Creating patched IPSW (this will take several minutes)
Replacing bootchain components
Extracting ramdisk from IPSW
Patching ramdisk
cat: stdout: No space left on device

I tried redownloading everything but nothing, Am I doing something wrong?

**Comment by parrotgeek1** [comment]
Fixed in master branch. releases never had this issue
