### ISSUE TITLE
cat: stdout: no space left on device

### ISSUE THREAD

**Issue by lippaim** [parrotgeek1/Pluvia#23]
Hello,

I am getting the following error  when running pluvia, after giving the  "./make_ipsw.sh " command

Extracting iBoot from IPSW
Patching iBoot
Creating patched IPSW (this will take several minutes)
Replacing bootchain components
Extracting ramdisk from IPSW
Patching ramdisk
cat: stdout: No space left on device

Any ideas what could be causing this?

**Comment by parrotgeek1** [comment]
What iOS version are you trying to create an IPSW for?

**Comment by lippaim** [comment]
> What iOS version are you trying to create an IPSW for?

Phone is on 7.1.2, trying to create ipsw for 6.1.2

**Comment by parrotgeek1** [comment]
I am able to successfully create a 6.1.2 IPSW with the latest code.
