### ISSUE TITLE
Revert Back

### ISSUE THREAD

**Issue by festo95** [parrotgeek1/Pluvia#25]
Hi I tried your project and it is awesome, iPhone 4 looks great on iOS 5.1.1, but I got an issue:
I can't go back to iOS 7, I want to try some other project and I need it, but when I use iTunes to restore or upgrade the device I face an unexpected error and a Bricked device, which can be restored only using Pluvia and run iOS 5 again, Is there a way to revert back to full stock iOS 7?

**Comment by parrotgeek1** [comment]
There are instructions in the read me about how to create and restore a reset ipsw to fix this issue.
