### ISSUE TITLE
ERROR: No Apple device in DFU Mode 0x1227 detected. Exiting.

### ISSUE THREAD

**Issue by HexagonWin** [parrotgeek1/Pluvia#30]
Hi. I have a iPhone3,1.
This phone was originally downgraded to 6.1.6 in a Sierra Hackintosh PC.
I returned it to iOS 7.1.2.
Now i want to downgrade again to 5.1.1 but now i dont have the old pc that i used and instead i have a mojave 10.14.4 hackintosh.
(it is intel!)
when trying downgrade, the ipsw build is successed. but when i do ./restore.sh iPhone3,1_5.1.1_9B206_Restore_Patched_JB.ipsw
i get the error in the title.
i trired running with root but no success
please help! thanks

**Comment by parrotgeek1** [comment]
I developed Pluvia on Mojave; maybe there's an issue with your USB drivers?
