### ISSUE TITLE
m,y iphone is stuck in recovery mode perm after restore from ios 5.1.1 using this downgrade

### ISSUE THREAD

**Issue by robertThe4** [parrotgeek1/Pluvia#34]
i downgraded both my iphone 4's to ios 5.1.1 then when i got bored of ios 5.1.1 i restored back to ios 7.1.2 then it was in recovery mode after restore i tried restoring again and still in recovery mode i tried everything on the internet and i gave my phones to a repair shop if they can not fix it what do i do?

**Comment by parrotgeek1** [comment]
A procedure to fix this issue is in the readme, under the section "Getting out of recovery mode after restoring to stock iOS".
