### ISSUE TITLE
Pluvia Errors

### ISSUE THREAD

**Issue by DolphinFlopFish** [parrotgeek1/Pluvia#35]
Hello, When I try to restore iOS 5.1.1 on to my iPhone 4 GSM (3,1) on OS X 10.9 Mavericks (on a 2010 MacBook 7,1) I run into a "curl" certificate error. I downloaded the iPhone 4 GSM 7.1.2 IPSW File from ipsw.me and put it in my downloads folder and it still did not work! I ran these commands in the terminal:
cd /Users/myname/Downloads/Pluvia-main
./make_ipsw.sh /Users/myname/Downloads/iPhone3,1_5.1.1_9B206_Restore.ipsw
Then I get a curl certificate error. Please help, thank you!

**Comment by parrotgeek1** [comment]
The version of libcurl included in OS X 10.9 Mavericks is not new enough to support TLS 1.2. This can't be easily fixed, and affects much more software than Pluvia.

**Comment by DolphinFlopFish** [comment]
are there any alternatives to pluvia that work on OS X 10.9??

**Comment by parrotgeek1** [comment]
There aren't. Honestly I would recommend you to be on at least El Capitan;
I haven't tested it on yosemite either.

**Comment by DolphinFlopFish** [comment]
Ok thanks for your help! I might consider upgrading to El Capitan
