### ISSUE TITLE
Pluvia iPhone 5,2

### ISSUE THREAD

**Issue by DolphinFlopFish** [parrotgeek1/Pluvia#36]
Are there any other tools like pluvia that will work on the iphone 5,2?
I really want to put iOS 6.1.3 onto my iPhone 5

Also I used Pluvia on OS X 10.11 and it worked! This is the best tool ever

**Comment by parrotgeek1** [comment]
There are not unfortunately, unless you happen to be on iOS 7.0.4-7.0.6, then there's ch3rryfl0wer.

FYI my email address is on my website, it's a much easier way to contact me.
