### ISSUE TITLE
iOS 4 support

### ISSUE THREAD

**Issue by Computershik73** [parrotgeek1/Pluvia#42]
Please add iOS 4 support, we really need it.

**Comment by parrotgeek1** [comment]
To be honest, I'm losing interest in legacy iOS development. Even iOS 6 is starting to become nearly unusable for some purposes (apps don't work anymore, half broken Siri, no weather) and iOS 4 is even worse in terms of compatibility. I doubt I will support iOS 4 in Pluvia. I know that's disappointing, but I don't want to work on something that I have no personal interest in.
