### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by a8q** [parrotgeek1/Pluvia#9]
Please Credit:
- [me](https://twitter.com/SynAck__) for the partitioning script (from [here](https://github.com/a8q/De-Rebus-Ramdisk/blob/master/java/gui/sshtar/bin/part.sh))
- [@xerub](https://twitter.com/xerub) For De Rebus Antiquis
- [@dora_IOS](https://twitter.com/dora_iOS) for the untethered ramdisk
- [p0sixpwn for the iOS 6 bootstrap](https://github.com/p0sixspwn/p0sixspwn)
- Also please remove (what I believe to be) redsn0w's bootstrap. As per their licence (I grabbed relevent pieces):

```
Copyright 2007-2012 iPhone Dev-Team. All rights reserved. Not for commercial use. 

The resale of this application (redsn0w) is strictly prohibited, modification and redistribution of this applications are strictly prohibited.
```
you absolutely should not be using their stuff.

- EDIT - You should also credit @Dora_iOS for the Firmware bundles *I believe*

**Comment by AxiomYT** [comment]
Actually I posted this in the wrong place - credit people next time @parrotgeek1 

will NOT be anticipating iOS 5 like i would like so much to do. could someone else give me a hand?

**Comment by AxiomYT** [comment]
well fuck you too then 

lots of love x

**Comment by parrotgeek1** [comment]
Re: Credit - sorry. Will do that ASAP

Cydia.tar is not from redsn0w. I don't even remember where I got it, but it's completely composed of deb files from saurik's repo and can't possibly be subject to redsn0w's license.

**Comment by parrotgeek1** [comment]
@AxiomYT I deleted your comments because you posted them in an irrelevant thread. Now I have to delete that one too because you swore at me. iOS 5 support is coming in a week or two.

**Comment by a8q** [comment]
Ahh ok. Took a look, seems to be an updated version of the Redns0w bootstrap *probably* fine.

**Comment by parrotgeek1** [comment]
Even if it were identical, redsn0w didn't change/add any code to it and can't just relicense it themselves. That license only covers redsn0w itself.

**Comment by a8q** [comment]
That's debatable. Don't forget Saurik is part of the iPhone dev team

**Comment by parrotgeek1** [comment]
What I am trying to say is that I could, using public debs, create an IDENTICAL file to that tar that is not subject to the license.

**Comment by a8q** [comment]
Either way.. Please credit people when you use their work

**Comment by a8q** [comment]
Thank you.

**Comment by parrotgeek1** [comment]
Hey @a8q can you accept my invite to Pluvia 2 dev repo?
